# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tsafe 0.0.12 ruby lib

Gem::Specification.new do |s|
  s.name = "tsafe"
  s.version = "0.0.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kasper Johansen"]
  s.date = "2016-02-08"
  s.description = "Proxy-objects for making another object threadsafe by proxying calls through mutex and method_missing. Monitored array and hash where all methods are going through monitor. Threadsafe class for including into a class that extends another class in order to make it threadsafe."
  s.email = "k@spernj.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".rubocop_todo.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/tsafe.rb",
    "lib/tsafe_monarray.rb",
    "lib/tsafe_monhash.rb",
    "lib/tsafe_monitored.rb",
    "lib/tsafe_mrswlock.rb",
    "lib/tsafe_mrswlock_jruby.rb",
    "lib/tsafe_mrswlock_synmodule.rb",
    "lib/tsafe_mutexed.rb",
    "lib/tsafe_proxy.rb",
    "shippable.yml",
    "spec/mrswlock_spec.rb",
    "spec/spec_helper.rb",
    "spec/tsafe_spec.rb",
    "tsafe.gemspec"
  ]
  s.homepage = "http://github.com/kaspernj/tsafe"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Threadsafe proxy, array, hash and framework for making other classes threadsafe."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<best_practice_project>, [">= 0"])
      s.add_development_dependency(%q<rubocop>, ["= 0.37.0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<best_practice_project>, [">= 0"])
      s.add_dependency(%q<rubocop>, ["= 0.37.0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<best_practice_project>, [">= 0"])
    s.add_dependency(%q<rubocop>, ["= 0.37.0"])
  end
end

